# Generated by Django 4.2.3 on 2024-04-14 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="title",
        ),
    ]
